# - name: Erase all data
#   shell: "rm -rf {{ item.mount_point }}/*"
#   ignore_errors: yes
#   loop: "{{ disks }}"
#   loop_control:
#     extended: yes
#   register: output
# - debug: var=output.results

- name: Create BeeGFS working dirs on server nodes
  shell: "mkdir -p {{ item.mount_point }}/*"
  ignore_errors: no
  loop: "{{ disks }}"
  loop_control:
    extended: yes

- name: Create log directory
  shell: "mkdir -p {{ log_dir }}"
  register: output
- debug: var=output

#- name: Create beegfs working directory
#  shell: "mkdir -p {{ first_disk }}/{{ ansible_user_id }}"
#  register: output
#- debug: var=output

