# - name: Erase all data
#   shell: "rm -rf {{ item.mount_point }}/*"
#   ignore_errors: yes
#   loop: "{{ disks }}"
#   loop_control:
#     extended: yes
#   register: output
# - debug: var=output.results
- name: Create logging directory
  shell: "mkdir -p {{ log_dir }}"
  register: output
- debug: var=output.stdout_lines
