dsrp:
  root_dir: /users/ftessier/dynamic-resource-provisioning
resources:
  system: dom
  job_id_env: SLURM_JOB_ID
  inventory_file: inventory.yml
  compute_nodes:
    scheduler_nodelist_env: SLURM_NODELIST_PACK_GROUP_0
  storage_nodes:
    scheduler_nodelist_env: SLURM_NODELIST_PACK_GROUP_1
    disks_per_node: 3
data_manager:
  type: beegfs
  server:
    start: start_beegfs_servers.yml
    stop: stop_beegfs_servers.yml
  client:
    start: mount_beegfs_clients.yml
    stop: umount_beegfs_clients.yml
