resources:
  system: dom
  inventory_file: nodelist.yml
  storage_nodes:
    scheduler_nodelist_env: SLURM_JOB_NODELIST
    disks_per_node: 3
  compute_nodes:
    scheduler_nodelist_env: SLURM_JOB_NODELIST
data_manager:
  type: beegfs
  server:
    start: start_beegfs_servers.yml
    stop: stop_beegfs_servers.yml
  client:
    start: mount_beegfs_clients.yml
    stop: umount_beegfs_clients.yml
