- name: Template BeeGFS management configuration file
  template:
    src: "{{ template_dir }}/beegfs-mgmtd.conf"
    dest: "{{ mgmtd_conf_file }}"
    
- name: Deploy containerized BeeGFS management service
  shell: "{{ sarus_base_cmd }}
          --mount=type=bind,source={{ mgmtd_conf_file }},destination=/{{ mgmtd_conf_filename }}
           {{ container }}
           /opt/beegfs/sbin/beegfs-mgmtd cfgFile=/{{ mgmtd_conf_filename }} pidFile={{ mgmtd_pid_file }} &"
  register: output
- debug: var=output.stdout_lines
