---
#####################
# All nodes         #
#####################
- hosts: compute_nodes
  gather_facts: False

  tasks:
    - set_fact: template_dir="{{ root_dir }}/playbooks/beegfs/templates"
    - set_fact: config_dir="{{ root_dir }}/playbooks/beegfs/configurations"

#####################
# BeeGFS Client     #
#####################
- hosts: compute_nodes
  gather_facts: False
  vars:
    host_idx: "{{ groups['compute_nodes'].index(inventory_hostname) }}"
  roles:
    - client
