---
#####################
# All nodes         #
#####################
- hosts: compute_nodes
  strategy: free
  gather_facts: False
  tasks:
    - set_fact: template_dir="{{ playbook_dir }}/templates"
    - set_fact: config_dir="{{ playbook_dir }}/configurations"
    - set_fact: container_run="{{ container_runtime_cmd }} {{ container_runtime_mnt }}"
    - set_fact: container="henriquemendonca/beegfs:deb9"


#####################
# BeeGFS Client     #
#####################
- hosts: compute_nodes
  strategy: free
  gather_facts: False
  vars:
    host_idx: "{{ groups['compute_nodes'].index(inventory_hostname) }}"
  roles:
    - mount_client
