---
#####################
# All nodes         #
#####################
- hosts: compute_nodes
  gather_facts: False

  tasks:
    - set_fact: template_dir="{{ playbook_dir }}/templates"
    - set_fact: config_dir="{{ playbook_dir }}/configurations"

#####################
# BeeGFS Client     #
#####################
- hosts: compute_nodes
  gather_facts: False
  vars:
    host_idx: "{{ groups['compute_nodes'].index(inventory_hostname) }}"
  roles:
    - mount_client
