---
#####################
# All nodes         #
#####################
- hosts: compute_nodes
  gather_facts: False

  #####################
  # BeeGFS Client     #
  #####################
  roles:
    - client
