---
- hosts: storage_nodes
  gather_facts: False

  tasks:
    - set_fact: first_disk="{{ disks[0].mount_point }}/{{ lookup('env','USER') }}"
    - set_fact: log_dir="{{ first_disk }}/log"
    - set_fact: template_dir="{{ playbook_dir }}/templates"
    - set_fact: config_dir="{{ playbook_dir }}/configurations"
    - set_fact: container_run="{{ container_runtime_cmd }} {{ container_runtime_mnt }}"
    - set_fact: container="henriquemendonca/beegfs:deb9"

#####################
# All nodes         #
#####################
- hosts: storage_nodes
  gather_facts: False
  roles:
    - common
       
#####################
# Nodes 0 only      #
#####################
- hosts: storage_nodes[0]
  gather_facts: False
  roles:
    - start_mgmtd
#    - start_admon

#####################
# All nodes         #
#####################
- hosts: storage_nodes
  gather_facts: False
  vars:
    host_idx: "{{ groups['storage_nodes'].index(inventory_hostname) }}"
  roles:
    - start_meta
    - start_storage

# - pause:
#     seconds: 30
