---
- hosts: storage_nodes
  gather_facts: True

  tasks:
    - set_fact: first_disk="{{ disks[0].mount_point }}"

#####################
# All nodes         #
#####################
- hosts: storage_nodes
  vars:
    host_idx: "{{ groups['storage_nodes'].index(inventory_hostname) }}"
  roles:
    - stop_meta
    - stop_storage

#####################
# Nodes 0 only      #
#####################
- hosts: storage_nodes[0]
  roles:
#    - stop_admon
    - stop_mgmtd
