---
- hosts: storage_nodes
  gather_facts: False

  tasks:
    - set_fact: first_disk="{{ disks[0].mount_point }}"
    - set_fact: log_dir="{{ first_disk }}/log"
    - set_fact: template_dir="{{ playbook_dir }}/templates"
    - set_fact: config_dir="{{ playbook_dir }}/configurations"
    - set_fact: container_run="{{ container_runtime_cmd }} --entrypoint {{ container_runtime_mnt }}"
    - set_fact: container="ceph/daemon"

#####################       
# All nodes         #
#####################
- hosts: storage_nodes
  gather_facts: False
  roles:
    - common

#####################       
# Node 0 only       #
#####################
- hosts: storage_nodes[0]
  gather_facts: False
  roles:
    - start_monitor
