---
- hosts: storage_nodes
  gather_facts: False

  tasks:
    - set_fact: template_dir="{{ root_dir }}/playbooks/ceph/templates"
    - set_fact: config_dir="{{ root_dir }}/playbooks/ceph/configurations"
    - set_fact: container_run="{{ container_runtime_cmd }} --entrypoint {{ container_runtime_mnt }}"
    - set_fact: container="ceph/daemon"

#####################       
# All nodes         #
#####################
- hosts: storage_nodes
  gather_facts: False
  roles:
    - common

#####################       
# Node 0 only       #
#####################
- hosts: storage_nodes[0]
  gather_facts: False
  roles:
    - start_monitor
