all:
  children:
    compute_nodes:
      hosts: null
    master:
      hosts:
        dom101:
          ansible_connection: ssh
    storage_nodes:
      hosts:
        nid000[52-55]: null
      vars:
        disks:
        - model: MZPLL6T4HMLS-00003
          mount_point: /mnt/nvme0n1/{{ ansible_user_id }}
          name: nvme0n1
          size: 5.9T
          vendor: SAMSUNG
        - model: MZPLL6T4HMLS-00003
          mount_point: /mnt/nvme1n1/{{ ansible_user_id }}
          name: nvme1n1
          size: 5.9T
          vendor: SAMSUNG
        - model: MZPLL6T4HMLS-00003
          mount_point: /mnt/nvme2n1/{{ ansible_user_id }}
          name: nvme2n1
          size: 5.9T
          vendor: SAMSUNG
  hosts: null
