- name: Kill containerized BeeGFS storage service
  #vars:
  #  storage_name: "beegfs-storage-{{ host_idx }}-{{ item.name }}"
  #  storage_pid_file: "{{ item.mount_point }}/{{ lookup('env','USER') }}/{{ storage_name }}.pid"
  #  storage_conf_filename: "{{ storage_name }}.conf"
  shell: pkill  "beegfs-storage"
  ignore_errors: yes
  #loop: "{{ disks }}"
  #loop_control:
  #  extended: yes
  #register: output
- debug: var=output
