dsrp:
  root_dir: /users/ftessier/dynamic-resource-provisioning
resources:
  system: dom
  job_id_env: SLURM_JOB_ID
  inventory_file: inventory.yml
  compute_nodes:
    scheduler_nodelist_env: 
  storage_nodes:
    scheduler_nodelist_env: SLURM_NODELIST
    disks_per_node: 3
data_manager:
  type: minio
  server:
    start: start_minio_servers.yml
    stop: stop_minio_servers.yml
  client:
    stop:
