---
- hosts: storage_nodes
  gather_facts: False

  tasks:
  - name: Create an archive for each disk
    archive:
      path:
      - "{{ item.mount_point }}/*"
      dest: "{{ item.mount_point }}/{{ item.name }}.tar.gz"
      format: gz
      force_archive: true
    loop: "{{ disks }}"
    loop_control:
      extended: yes
    register: output
  - debug: var=output.results

  - name: Create destination directory if it does not exist
    file:
      path: "{{ stage_out_path }}/{{ inventory_hostname }}"
      state: directory
      mode: '0755'
      
  - name: Copy files from disks to long-term persistent storage
    copy:
      src: "{{ item.mount_point }}/{{ item.name }}.tar.gz"
      dest: "{{ stage_out_path }}/{{ inventory_hostname }}/{{ item.name }}.tar.gz"
      remote_src: true
    loop: "{{ disks }}"
    loop_control:
      extended: yes
    register: output
  - debug: var=output.results


