- name: Umount BeeGFS on the compute node
  shell: "sudo {{ umount_cmd }} -t beegfs -l {{ client_mount_point }}"
  register: output
- debug: var=output.stdout_lines

- name: Kill containerized BeeGFS helperd service
  shell: pkill "beegfs-helperd"
  ignore_errors: yes
  register: output
- debug: var=output
