- name: Deploy native BeeGFS helperd service
  shell: "/opt/beegfs/sbin/beegfs-helperd  cfgFile={{ client_helperd_conf }}"
  async: 604800  # 60*60*24*7 – 7 days
  poll: 0
  register: output
- debug: var=output

- name: Mount BeeGFS on the compute node
  shell: "sudo {{ mount_cmd }} -t beegfs beegfs_nodev {{ client_mount_point }} -ocfgFile={{ client_conf_file }},_netdev,,"
  register: output
- debug: var=output

