- name: Template BeeGFS client configuration file
  template:
    src: "{{ template_dir }}/beegfs-client.conf"
    dest: "{{ client_conf_file }}"

- name: Template BeeGFS helperd configuration file
  template:
    src: "{{ template_dir }}/beegfs-helperd.conf"
    dest: "{{ client_helperd_conf }}"

- name: Create directory to mount BeeGFS
  shell: "mkdir -p {{ client_mount_point }}"
  register: output
- debug: var=output

- name: Deploy native BeeGFS helperd service
  shell: "/opt/beegfs/sbin/beegfs-helperd  cfgFile={{ client_helperd_conf }}"
  async: 604800  # 60*60*24*7 – 7 days
  poll: 0
  register: output
- debug: var=output


- name: Mount BeeGFS on the compute node
  shell: "sudo {{ mount_cmd }} -t beegfs beegfs_nodev {{ client_mount_point }} -ocfgFile={{ client_conf_file }},_netdev,,"
  register: output
- debug: var=output

