- name: Create BeeGFS configuration dir for this job
  local_action:
    module: ansible.builtin.file
    path: "{{ config_dir }}"
    state: directory

- name: Generate connauthfile from random
  local_action:
    module: ansible.builtin.shell
    cmd: "dd if=/dev/random of={{ config_dir }}/connauthfile bs=1 count=128"

- name: Set connauthfile with 644 permissions
  local_action:
    module: ansible.builtin.file
    path: "{{ config_dir }}/connauthfile"
    state: file
    # must be readable by others for sudo mounting
    mode: '644'

- name: Template BeeGFS client configuration file
  local_action:
    module: ansible.builtin.template
    src: "{{ template_dir }}/beegfs-client.conf"
    dest: "{{ config_dir }}/beegfs-client.conf"

- name: Template BeeGFS helperd configuration file
  local_action:
    module: ansible.builtin.template
    src: "{{ template_dir }}/beegfs-helperd.conf"
    dest: "{{ config_dir }}/beegfs-helperd.conf"

- name: Template BeeGFS management configuration file
  local_action:
    module: ansible.builtin.template
    src: "{{ template_dir }}/beegfs-mgmtd.conf"
    dest: "{{ mgmtd_conf_file }}"

- name: Deploy containerized BeeGFS management service
  shell: "{{ container_run }} --mount=type=bind,source={{ mgmtd_conf_file }},destination=/{{ mgmtd_conf_filename }} --mount=type=bind,source={{ config_dir }}/connauthfile,destination=/etc/beegfs/connauthfile --entrypoint={{ mgmtd_bin }}  {{ container }}  cfgFile=/{{ mgmtd_conf_filename }} pidFile={{ mgmtd_pid_file }}"
  async: 604800  # 60*60*24*7 – 7 days
  poll: 0
  register: output
- debug: var=output

