- name: Template BeeGFS management configuration file
  template:
    src: "{{ template_dir }}/beegfs-mgmtd.conf"
    dest: "{{ mgmtd_conf_file }}"
    
- name: Deploy containerized BeeGFS management service
  shell: "{{ container_run }}
          --mount=type=bind,source={{ mgmtd_conf_file }},destination=/{{ mgmtd_conf_filename }}
           {{ container }}
           {{ mgmtd_bin }} cfgFile=/{{ mgmtd_conf_filename }} pidFile={{ mgmtd_pid_file }}"
  async: 604800  # 60*60*24*7 – 7 days
  poll: 0
  register: output
- debug: var=output
