- name: Start MinIO servers
  vars:
    minio_access_key: "IiaFsQIpRM"
    minio_secret_key: "gQbENgqvagxFt59j4U46m4dwL83kBQmf"
    
  shell: "{{ container_run }}
          {{ container }}
          /usr/bin/docker-entrypoint.sh
          server
          {% for d in disks %}
          {% for n in groups['storage_nodes'] %}
          http://{{ n }}{{ d.mount_point }}/MinIO
          {% endfor %}
          {% endfor %} &> /dev/null &"
  environment:
    MINIO_ACCESS_KEY: "{{ minio_access_key }}"
    MINIO_SECRET_KEY: "{{ minio_secret_key }}"
  register: output
- debug: var=output
