mgmtd_name: "beegfs-mgmtd-0"
mgmtd_bin: "/opt/beegfs/sbin/beegfs-mgmtd"
mgmtd_dir: "{{ first_disk }}/{{ mgmtd_name }}"
mgmtd_log_file: "{{ log_dir }}/{{ mgmtd_name }}.log"
mgmtd_pid_file: "{{ first_disk }}/{{ mgmtd_name }}.pid"
mgmtd_conf_filename: "{{ mgmtd_name }}.conf"
mgmtd_conf_file: "{{ config_dir }}/{{ mgmtd_conf_filename }}"
mgmtd_daemonized: "false"
helperd_log_file: "{{ lookup('env','SCRATCH') }}/beegfs-helperd.log-{{ lookup('env','HOSTNAME') }}"
mgmtd_host: "{{ groups['storage_nodes'][0] }}"
