- name: Erase all data
  shell: "rm -rf {{ item.mount_point }}/cassandra"
  ignore_errors: yes
  loop: "{{ disks }}"
  loop_control:
    extended: yes
  register: output
- debug: var=output.results
  
- name: Create Cassandra directory on disks
  shell: "mkdir {{ item.mount_point }}/cassandra"
  loop: "{{ disks }}"
  loop_control:
    extended: yes
  register: output
- debug: var=output.stdout_lines
