---
- hosts: storage_nodes
  strategy: free
  gather_facts: False
  tasks:
    - set_fact: template_dir="{{ root_dir }}/playbooks/cassandra/templates"
    - set_fact: config_dir="{{ root_dir }}/playbooks/cassandra/configurations"
    - set_fact: container_run="{{ container_runtime_cmd }} {{ container_runtime_mnt }}"
    - set_fact: container="cassandra"

- hosts: storage_nodes[0]
  gather_facts: False
  roles:
    - configure_jmx

- hosts: storage_nodes
  strategy: free
  gather_facts: False
  roles:
    - setup_disks
    - start_server
