---
- hosts: master
  strategy: free
  gather_facts: False
  tasks:
    - set_fact: container_run="{{ container_runtime_cmd }} {{ container_runtime_mnt }}"
    - set_fact: container="cassandra"

- hosts: master
  strategy: free
  gather_facts: False
  roles:
    - stop_server
